[workspace]
members = [
    "crates/bulletproofs-cycle",
    "crates/golden-core",
    "crates/golden-ehtdh1",
    "crates/golden-evrf",
    "crates/golden-halo2curves",
    "crates/golden-rustcrypto",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/0xMiden/golden-dkg"
rust-version = "1.86"

[workspace.dependencies]
bulletproofs = { version = "5.0.0", default-features = false }
bulletproofs-cycle = { path = "crates/bulletproofs-cycle" }
chacha20 = "0.9"
curve25519-dalek = { version = "4.1.3", default-features = false }
ff = { version = "0.13", default-features = false }
group = { version = "0.13", default-features = false }
golden-core = { path = "crates/golden-core" }
golden-evrf = { path = "crates/golden-evrf" }
golden-halo2curves = { path = "crates/golden-halo2curves" }
halo2curves = { version = "0.10", default-features = false }
hex = "0.4"
hkdf = "0.12"
k256 = { version = "0.13", default-features = false }
merlin = { version = "3", default-features = false }
rand_chacha = "0.3"
rand_core = "0.6"
sha2 = "0.10"
sha3 = { version = "0.10", default-features = false }
subtle = "2.6"
thiserror = "2"
zeroize = "1.8"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
unwrap_used = "deny"
panic = "deny"
