[package]
name = "golden-halo2curves"
version = "0.4.0"
description = "Halo2 curve adapters for Golden distributed key generation"
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
publish = ["crates-io"]

[dependencies]
bulletproofs-cycle = { workspace = true }
ff = { workspace = true }
golden-core = { workspace = true }
group = { workspace = true }
halo2curves = { workspace = true, features = ["std"] }
rand_core = { workspace = true }
subtle = { workspace = true }

# NOTE: This prevents cross-compilation from ARM.
[target.'cfg(target_arch = "x86_64")'.dependencies]
halo2curves = { workspace = true, features = ["asm"] }

[dev-dependencies]
merlin = { workspace = true }
rand_chacha = { workspace = true }

[features]
default = []
halo2curves-secp256k1 = []

[lints]
workspace = true
