[package]
name = "golden-core"
version = "0.1.0"
description = "Core traits and protocols for Golden distributed key generation"
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
publish = ["crates-io"]

[dependencies]
miden-serde-utils = { workspace = true, optional = true }
rand_core = { workspace = true }
serde = { workspace = true, optional = true }
sha2 = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
rand_chacha = { workspace = true }
serde_test = { workspace = true }

[features]
default = []
miden-serde = ["dep:miden-serde-utils"]
serde = ["dep:serde"]

[lints]
workspace = true
